{
 "title": "Per Process Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   { "name": "inter", "label": "Sampling", "query": "1s,5s,10s,30s,1m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_vms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Process RSS Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "query": "SELECT max(\"memory_rss\") FROM \"procstat\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($interval), \"process_name\"",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes waiting on IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_time_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}